definitions:
  helper.HTTPResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: string
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validation.ValidationError'
        type: array
    type: object
  validation.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /register-login-mobile/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register Login
      parameters:
      - description: Mobile number
        in: formData
        name: mobile
        required: true
        type: string
      - description: OTP
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: User Auth
      tags:
      - auth
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Health Check
      tags:
      - health
swagger: "2.0"
