basePath: /api/v1
definitions:
  helper.HTTPResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: string
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validation.ValidationError'
        type: array
    type: object
  validation.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
host: localhost:5005
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is my API server.
  title: My API
  version: "1.0"
paths:
  /c/assign/cities:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Assign a list of cities to a specified country by country ID
      parameters:
      - collectionFormat: csv
        description: Array of city names
        in: formData
        items:
          type: string
        name: cities
        required: true
        type: array
      - description: Country ID
        in: formData
        name: countryid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Assign cities to a country
      tags:
      - country
  /c/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create a new country
      parameters:
      - description: country name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Country
      tags:
      - country
  /c/delete:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Delete country
      parameters:
      - description: country id
        in: formData
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Country
      tags:
      - country
  /c/get/{id}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get country
      parameters:
      - description: country id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Country
      tags:
      - country
  /c/get/all:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get country
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Country
      tags:
      - country
  /c/update:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Update country
      parameters:
      - description: country name
        in: formData
        name: name
        required: true
        type: string
      - description: country id
        in: formData
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Country
      tags:
      - country
  /claim/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register Login
      parameters:
      - description: jwt token
        in: formData
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - AuthBearer: []
      summary: Get Claims
      tags:
      - auth
  /register-login-mobile/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register Login
      parameters:
      - description: Mobile number
        in: formData
        name: mobile
        required: true
        type: string
      - description: OTP
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: User Auth
      tags:
      - auth
  /register/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register
      parameters:
      - description: first name
        in: formData
        name: firstName
        required: true
        type: string
      - description: last name
        in: formData
        name: lastName
        required: true
        type: string
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: User Auth
      tags:
      - auth
  /send-otp/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: OTP request
      parameters:
      - description: mobile
        in: formData
        name: mobile
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Send OTP request
      tags:
      - auth
  /up-login/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register Login up
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: User Auth up
      tags:
      - auth
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Health Check
      tags:
      - health
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
